name: CI/CD Pipeline for QueuingAssignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run Tests
        run: php vendor/bin/phpunit --testdox

  docker-build-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/queuing-assignment:latest .
          docker tag your-dockerhub-username/queuing-assignment:latest your-dockerhub-username/queuing-assignment:v1.0

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-dockerhub-username/queuing-assignment:latest
          docker push your-dockerhub-username/queuing-assignment:v1.0

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS
        run: echo "Deployment step to AWS goes here (e.g., AWS Elastic Beanstalk or EC2)"
